import {
  Bookmark,
  Chat,
  Group,
  HelpOutline,
  Home,
  Menu,
  PlayCircleFilled,
  RssFeed,
  WorkOutline,
  Event,
  School,
} from "@mui/icons-material";
export const leftBarItems = [
  { component: Home, title: "Home" },
  { component: Menu, title: "Menu" },
  { component: RssFeed, title: "Feeds" },
  { component: Chat, title: "Chats" },
  { component: Group, title: "Groups" },
  { component: Bookmark, title: "Bookmarks" },
  { component: HelpOutline, title: "Questions" },
  { component: WorkOutline, title: "Jobs" },
  { component: PlayCircleFilled, title: "Videos" },
  { component: Event, title: "Events" },
  { component: School, title: "Courses" },
];
